### PR TITLE
Add GtkIMMulticontext and GtkIMContext

### PR DESCRIPTION
**Pull request by daa84**
Add GtkIMMulticontext and GtkIMContext objects.

### CODE REVIEW

**Comment by EPashkin** [comment]
@daa84 This also need generating InputHints, InputPurpose. See travis log

**Comment by daa84** [comment]
Hm, looks like cfg(feature = "v3_6") needed for InputHints, but how to set it?

**Comment by EPashkin** [comment]
See https://github.com/gtk-rs/gtk/blob/master/Gir.toml#L435-L437

**Comment by daa84** [comment]
Thanks :+1:

**Comment by EPashkin** [comment]
Thanks.
If travis passed, squash all commits please

**Comment by daa84** [comment]
done.

**Comment by EPashkin** [comment]
@GuillaumeGomez 👍 for this and CI passed

**Comment by GuillaumeGomez** [comment]
Thanks!

**Pull request merged**
