### PR TITLE
Enums

### PR DESCRIPTION
**Pull request by EPashkin**
Part of #307
Do not merge until all parts done

### CODE REVIEW

**Comment by EPashkin** [comment]
Build of this PR IMHO better restarted after merging `gdk` part, it must builds.

**Comment by gkoz** [comment]
A big question here is are there any enums that appear as return values, that we don't want to have the `__Nonexhaustive` member, i.e. keep exhaustive matches possible for them?

The error enums to add can be found by the `glib:error-domain` attribute. We'll at least want `BuilderError`, `FileChooserError`, `RecentChooserError`.

**Comment by EPashkin** [comment]
Agree that `__Nonexhaustive` unintuitive. Also on detailed look I don't understand what return enum's `from_glib` if ffi-value not in enum.

I add gtk's errors after gdk's PR merged to test build.

**Comment by EPashkin** [comment]
Checked that adding all 7 errors don't fail build.

**Comment by EPashkin** [comment]
Now I fully don't understand reason add `__Nonexhaustive` to enums as it checked only in `to_glib` and 
"defend" C++ code from rust.

**Comment by gkoz** [comment]
It's true that `from_glib` doesn't handle unexpected variants *now*, because enums in the sys crates are incapable of representing unexpected values. Once we finish this transition and stop reexporting enums from sys, they can be changed to `i32` typedefs or newtypes and then `from_glib` conversions can have the fallback arms.

**Comment by gkoz** [comment]
Shouldn't we remove all enum and flags reexports from `lib.rs`? Also this seems to have build errors unrelated to the gdk PR.

**Comment by EPashkin** [comment]
Strange, I see that all 15 errors from gdk.

**Comment by gkoz** [comment]
Might need to enable the `v3_16` feature to reproduce.

**Comment by EPashkin** [comment]
Though I misses `gtk` enums needed with `gtk_3_18` feature

**Comment by EPashkin** [comment]
@gkoz I ready to push fixed.
Is there any problem with gdk's PR? IMHO better merge it before push here, so we get normal build test.

**Comment by gkoz** [comment]
Fine, let's do this.

**Comment by EPashkin** [comment]
What to do with ./check_init_asserts errors?

**Comment by gkoz** [comment]
Oops, I wondered why this isn't an issue but it actually is... The generator should be inserting the 'skip' macro invocations.

**Comment by gkoz** [comment]
We could merge and fix that later.

**Comment by GuillaumeGomez** [comment]
@gkoz: I let you handle this PR (and this issue as well :p).

**Comment by EPashkin** [comment]
AppVeyor build succeeded

**Comment by gkoz** [comment]
Thanks @EPashkin for handling this. I'd rather we removed other reexports right away if they seem unused.

**Comment by EPashkin** [comment]
IMHO I removed all enums reexports, missed anything?

**Comment by gkoz** [comment]
Rigth, sorry, this only applies to gdk then.

A concern here is preserving a way to get a `i32` from `IconSize` until we override the type. We might recommend using `to_glib` for the time being...

**Pull request merged**
