### PR TITLE
Use glib's Inhibit

### PR DESCRIPTION
**Pull request by EPashkin**

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Wait... What?! XD

**Comment by EPashkin** [comment]
@GuillaumeGomez Sorry, I don't understand

**Comment by GuillaumeGomez** [comment]
I thought it'd take you more than 2 minutes to do the other updates.

**Comment by EPashkin** [comment]
Ah, it ready since first PR, just not added to skip build failures.

**Comment by GuillaumeGomez** [comment]
Thanks!

**Pull request merged**
