### PR TITLE
Remove deprecated style

### PR DESCRIPTION
**Pull request by EPashkin**
@gkoz You right, GtkStyle deprecated: https://developer.gnome.org/gtk3/stable/GtkStyleContext
So I remove it.
IMHO also better hide `"[gs]et_style"` in Widget with comment about deprecated and delete currently commented `Gtk.Style` section.

### CODE REVIEW

**Comment by EPashkin** [comment]
Also I remember that we decide do not hide deprecated objects long ago but there IMHO we have exception.

**Comment by EPashkin** [comment]
By "https://developer.gnome.org/gtk3/stable/GtkWidget.html" also deprecated in 3.0 widget "gtk_widget_ensure_style", "gtk_widget_size_request", "gtk_widget_get_child_requisition", "gtk_widget_set_state" (maybe with GtkStateType), "gtk_widget_reset_rc_styles" (with GtkRcStyle?), "gtk_widget_get_default_style", "gtk_widget_path", "gtk_widget_class_path", "gtk_widget_modify_style", "gtk_widget_get_modifier_style", "gtk_widget_modify_fg", "gtk_widget_modify_bg", "gtk_widget_modify_text", "gtk_widget_modify_base", "gtk_widget_modify_font", "gtk_widget_modify_cursor", "gtk_widget_render_icon", "gtk_widget_style_attach", "gtk_widget_get_state", "gtk_widget_has_rc_style", "gtk_widget_get_requisition" (with  GtkRequisition?).
Signals: state-changed, style-set.

**Comment by GuillaumeGomez** [comment]
Great, thanks!

**Comment by gkoz** [comment]
Huh, didn't realize there were so many of them. We might want to just hide any classes and methods that have deprecated version <= our minimum version (3.4 for gtk/gdk).

**Comment by EPashkin** [comment]
Removed all <=3.4. Used https://github.com/EPashkin/gir/tree/show_deprecation to checking

**Comment by gkoz** [comment]
I assume you don't like the idea of blanketly ignoring them in the generator based on `deprecated_version`? if doing it via the config we ought to add a comment to each ignored entry.

**Comment by EPashkin** [comment]
Added deprecated comment in gir.toml

**Comment by gkoz** [comment]
Thanks!

**Comment by EPashkin** [comment]
> I assume you don't like the idea of blanketly ignoring them in the generator based on deprecated_version? if doing it via the config we ought to add a comment to each ignored entry.

@gkoz I totally missed the first part, and did not even thought about it. Ignoring it with `gir` much better (if this option disabled by default). I do it.

**Pull request merged**
