### PR TITLE
Remove main_quit() assert

### PR DESCRIPTION
**Pull request by antoyo**

### CODE REVIEW

**Comment by EPashkin** [comment]
Something is broken with old code?

**Comment by antoyo** [comment]
Well, this assert does not seem to make sense.
For instance, if you manually run the loop like this:
```rust
while gtk::main_iteration() {
}
```
Calling `gtk::main_quit()` will panic in this case.

**Comment by EPashkin** [comment]
Thanks for explanation, 👍

**Comment by EPashkin** [comment]
`gtk_main_quit` really works in this cycle?
By https://gitlab.gnome.org/GNOME/gtk/blob/gtk-3-24/gtk/gtkmain.c#L1370 it just exit without main loop

**Comment by antoyo** [comment]
I'm not sure what you mean, but it will make `gtk_main_iteration()` returns `false`: https://gitlab.gnome.org/GNOME/gtk/blob/gtk-3-24/gtk/gtkmain.c#L1431

**Comment by antoyo** [comment]
Ah, I think I understand.
I'll test.

**Comment by antoyo** [comment]
So, you were right @EPashkin, `gtk_main_quit()` will output a CRITICAL error.
So, I'm closing this PR.

**Pull request closed without merging**
