### PR TITLE
subclass: Always allow to override the vfuns of classes

### PR DESCRIPTION
**Pull request by alatiera**

### CODE REVIEW

**Comment by alatiera** [comment]
Will also need to be backported to gtk4 bindings

**Comment by GuillaumeGomez** [comment]
:+1: 

cc @EPashkin @sdroege

**Comment by sdroege** [comment]
> Will also need to be backported to gtk4 bindings

Can you do that or create an issue?

**Comment by sdroege** [comment]
:+1:

**Comment by EPashkin** [comment]
@alatiera Thanks.
👍 after CI

**Comment by EPashkin** [comment]
@alatiera `cargo fmt` is needed: https://travis-ci.org/gtk-rs/gtk/jobs/607720361#L766

**Comment by alatiera** [comment]
> Can you do that or create an issue?

Can do after this is merged.

> @alatiera `cargo fmt` is needed: https://travis-ci.org/gtk-rs/gtk/jobs/607720361#L766

Should be good now.

**Comment by sdroege** [comment]
@GuillaumeGomez All green! :)

**Comment by GuillaumeGomez** [comment]
Thanks

**Pull request merged**
