### PR TITLE
Text signals

### PR DESCRIPTION
**Pull request by aethertap**
I added a `TextBufferSignals` trait in signals.rs so that you can subscribe to the "changed" signal, and added the changed signal to the `EntrySignals` trait. The implementations are just copied from other parts of the file.

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Hi ! Thanks for your PR. However, it seems your PR has more data than it should. Can you fix this please (just keep one commit and remove gtk-rs ones) ?

**Comment by aethertap** [comment]
Sure, sorry about that. This is my first PR on github (probably obvious).

**Comment by GuillaumeGomez** [comment]
No problem. Take your time and tell us when your PR is ready to be reviewed. :)

**Comment by aethertap** [comment]
Okay, I opened a new one that should be better, so I'll close this one.

**Pull request closed without merging**
