### PR TITLE
Add Buildable interface

### PR DESCRIPTION
**Pull request by federicomenaquintero**

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Looks good for me, thanks!

**Comment by federicomenaquintero** [comment]
Oops, I just updated the branch.  I had forgotten to put BuildableExtManual in prelude.rs.

**Comment by EPashkin** [comment]
As I remember we disable it for some reason, but not remember for what :(

**Comment by EPashkin** [comment]
Also please regen with right versions of gir and gir-files

**Comment by EPashkin** [comment]
About https://github.com/gtk-rs/glib/issues/219#issuecomment-325376884: this can cause need to specify trait function that need called, Ex. `Widget::set_name(&btn, "name")` instead `btn.set_name("name")`,
if this function is infrequently used, then its not big problem.

**Comment by federicomenaquintero** [comment]
Hmmm, I'm not convinced that my git submodules are set up correctly... I just did "make" and that downloaded them.  How can I check this?

set_name() is indeed not used very often; it's for styles and themes.

**Comment by GuillaumeGomez** [comment]
Ah, the dark magic of git submodules! :D

Once they're downloaded:

```bash
cd gir
git pull origin master
cd ../gir-files
git pull origin master
cd ..
make gir
```

Don't forget to commit `gir` and `gir-files`.

**Comment by federicomenaquintero** [comment]
I've rebased this to master, updated the submodules, and regenerated.  Now all the auto/* get the Buildable interface as appropriate.

**Comment by GuillaumeGomez** [comment]
:+1:

**Comment by EPashkin** [comment]
@federicomenaquintero  Thanks
👍 too.

**Comment by GuillaumeGomez** [comment]
Just waiting for CIs and then we merge. (please remind me if I forget!)

**Comment by EPashkin** [comment]
I restarted appveyour

**Comment by EPashkin** [comment]
CI passed here too.

**Comment by GuillaumeGomez** [comment]
Thanks!

**Comment by federicomenaquintero** [comment]
Awesome, thanks!

**Pull request merged**
