### PR TITLE
Print operation

### PR DESCRIPTION
**Pull request by EPashkin**
Closes https://github.com/gtk-rs/gtk/issues/595
cc @pwil3058

@GuillaumeGomez This based on https://github.com/gtk-rs/gtk/pull/594

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Is the regen commit still needed?

**Comment by EPashkin** [comment]
As 594 merged, only "Generate PrintOperation" will be added

**Comment by GuillaumeGomez** [comment]
That's what I'd think but I'm surprised by the fact the commit is still showing up. Generally, github hides it if it's already merged.

**Comment by EPashkin** [comment]
IMHO only if it was merged before PR started :(

**Comment by GuillaumeGomez** [comment]
Well, whatever. Once CI passed, I'll merge so it doesn't change much. ;)

**Comment by GuillaumeGomez** [comment]
Thanks!

**Pull request merged**
