### PR TITLE
Generate child properties

### PR DESCRIPTION
**Pull request by EPashkin**
Part of #392
Apply https://github.com/gtk-rs/gir/pull/299
WIP

### CODE REVIEW

**Comment by EPashkin** [comment]
Only last update gir submodule and regen

**Comment by EPashkin** [comment]
I almost forgot about renaming `Grid` childs to `cell`.
@GuillaumeGomez, @gkoz may be you also have meaningful names for some classes child's?

**Comment by GuillaumeGomez** [comment]
Nothing coming to my mind, so whatever the naming you pick, it's fine by me.

**Comment by EPashkin** [comment]
@GuillaumeGomez, merge https://github.com/gtk-rs/examples/pull/105, I finalizing this PR

**Comment by EPashkin** [comment]
Ready to merge

**Comment by GuillaumeGomez** [comment]
Thanks!

**Pull request merged**
