### PR TITLE
Add MenuBar

### PR DESCRIPTION
**Pull request by trolleyman**

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Thanks for your PR! I took a quick look and it seems correct but we'll also need @gkoz's confirmation.

**Comment by trolleyman** [comment]
Oh there's just one thing - I can't find a way to have a 'proper' menu bar. This one is not native, but I found [this](http://gtk-rs.org/docs/gtk_sys/fn.gtk_application_set_menubar.html) function in the docs, and was wondering if this is the way to create a proper menu bar?
For reference, MenuBar looks like this:

image

And native menus look like this:

image

**Comment by trolleyman** [comment]
Also Happy New Year!

**Comment by gkoz** [comment]
Okay doing `GMenuModel` definitely needs the object reform to be in place. I'm wrapping it up shortly and this issue can then progress.

**Comment by GuillaumeGomez** [comment]
@trolleyman: Thanks, you too! And just like @gkoz said, you'll have to be little bit patient, sorry about that.

**Comment by trolleyman** [comment]
Ok cool, thanks for doing this. Is [this](https://github.com/gkoz/gtk-rs-gtk/tree/object_reform) the object reform repo?

**Comment by gkoz** [comment]
The latest now is https://github.com/gkoz/gtk-rs-gtk/tree/object_reform_gir, it takes advantage of https://github.com/gkoz/gir, and there are some updates I haven't pushed yet

**Comment by gkoz** [comment]
I've looked into this and for the `GMenu` and friends bindings to be useful there need to be `GVariant` bindings. It's funny I've just finished dealing with `GValue` and here's another "variant datatype".

**Comment by gkoz** [comment]
But anyway adding `MenuBar` would go through `Gir.toml` now. See #232 for guidance.

**Comment by GuillaumeGomez** [comment]
I think we can close this issue now. Thanks anyway @trolleyman!

**Comment by wrnice** [comment]
Any news about this ? I am missing MenuBar a lot !

**Comment by GuillaumeGomez** [comment]
I think we could add them now since GValue binding has been done. Or something else is still missing @gkoz?

**Pull request closed without merging**
