### PR TITLE
regen

### PR DESCRIPTION
**Pull request by GuillaumeGomez**

### CODE REVIEW

**Comment by EPashkin** [comment]
Looks good for me, thanks

**Comment by sdroege** [comment]
:+1:

**Comment by GuillaumeGomez** [comment]
Failures are the usual ones so I'll just merge.

**Comment by sdroege** [comment]
Is a regen also needed for gio or any of the other crates, or did this really only affect gtk?

**Comment by GuillaumeGomez** [comment]
For all others repositories, it affected only commented functions. So I didn't open PRs for them.

**Pull request merged**
