### PR TITLE
Signals

### PR DESCRIPTION
**Pull request by EPashkin**
WIP
Build depends on https://github.com/gtk-rs/examples/pull/84 and fix `check_init_asserts`.
After merge https://github.com/gtk-rs/gir/pull/206 will be updated.

### CODE REVIEW

**Comment by EPashkin** [comment]
Currently "Regen" don't contains single-line changes to simplify review.
Also `src\signals.rs` still need manual check for duplicates.

**Comment by GuillaumeGomez** [comment]
Only removals in `src/signal`?

**Comment by EPashkin** [comment]
Yes, these replaced and compared with generated code.
I need check and remove others too.

**Comment by EPashkin** [comment]
Removed all generated manual signals, add to ignore some signals

**Comment by EPashkin** [comment]
AppVeyor is green.
PR still need update gir and full regen.

**Comment by gkoz** [comment]
What does the 'ns' note mean?

**Comment by EPashkin** [comment]
Namespaces https://github.com/gtk-rs/gir/issues/239

**Comment by EPashkin** [comment]
Final update.

**Comment by EPashkin** [comment]
Forgot restore `ScrollType` when restoring `RangeSignals`.

**Comment by gkoz** [comment]
It appears a significant number of signals need `Inhibit`, with varying degrees of certainty:
- `EntryCompletion`
- `Label::activate-link` (?)
- `LinkButton::activate-link`
- `MenuShell::move-selected`
- `Notebook::change-current-page` and others (??)
- `Paned` (?)
- `SpinButton::output` (?)
- `StatusIcon::size-changed`
- `Switch::state-set`
- `ToolItem::create-menu-proxy`
- `Toolbar`

Then, `IconView::activate-cursor`, `move-cursor` should be ignored, according to their docs. Or perhaps any "keybinding" signals should be, I'm not sure.

**Comment by EPashkin** [comment]
@gkoz Make it ignored in this PR?

**Comment by EPashkin** [comment]
Or only `IconView`s?

**Comment by gkoz** [comment]
I'm fine with ignoring provided we don't lose already implemented ones.

**Comment by EPashkin** [comment]
Copied list to https://github.com/gtk-rs/gir/issues/244

**Comment by EPashkin** [comment]
No `Inhibit` was in deleted signals.

**Comment by gkoz** [comment]
Thanks @EPashkin for this big piece of work, another significant step toward having comprehensive bindings.

@GuillaumeGomez?

Anyone up for updating the changelog with this and enums merge?

**Comment by GuillaumeGomez** [comment]
Amazing! Great job @EPashkin! Everything seems good for me. I merge.

**Comment by gkoz** [comment]
It appears the CI scripts don't properly test the `v3_16` feature :( and fail to catch this:
```
src/auto/gesture.rs:98:28: 98:34 error: type name `Object` is undefined or not in scope [E0412]
src/auto/gesture.rs:98 impl<O: IsA<Gesture> + IsA<Object>> GestureExt for O {
                                                  ^~~~~~
src/auto/gesture.rs:98:28: 98:34 help: run `rustc --explain E0412` to see a detailed explanation
src/auto/gesture.rs:98:28: 98:34 help: you can import several candidates into scope (`use ...;`):
src/auto/gesture.rs:98:28: 98:34 help:   `glib::Object`
src/auto/gesture.rs:98:28: 98:34 help:   `glib::object::Object`
```

**Comment by EPashkin** [comment]
It bad checking of signal count somewhere: checks total number of signals, not active.

**Comment by EPashkin** [comment]
`let extra_isa = if analysis.has_signals() { " + IsA<Object>" } else { "" };`

**Comment by EPashkin** [comment]
I fix it

**Comment by GuillaumeGomez** [comment]
@EPashkin: Thanks!
@gkoz: Any lead on why it doesn't fail?

**Comment by gkoz** [comment]
The scripts build the examples assuming they stress all features but the examples only enable `v3_10`... because I removed `gtk_3_18` to avoid confusing people with a complicated `Cargo.toml`. Ugh. We should just have an example, that uses something from 3.16 ;)

**Comment by EPashkin** [comment]
IMHO we need something like `gtk_3_18 = ["gtk_3_10", "gtk/v3_16"]` in examples,
so adding `default = ["gtk_3_18"]` will always use "last" gtk

**Comment by GuillaumeGomez** [comment]
@gkoz: Wasn't gl_area example supposed to be this example? :p

**Comment by gkoz** [comment]
At this point I don't expect the `GLArea` way to lead anywhere. I'd bet on someone implementing a GL 'backend' by extracting window handles from gdk.

**Pull request merged**
