### PR TITLE
Remove useless manual implementation

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
cc @EPashkin

### CODE REVIEW

**Comment by EPashkin** [comment]
Hm, duplicate implementation 😉.
Thanks.
👍 after error fixed.

**Comment by EPashkin** [comment]
@GuillaumeGomez, May be this too better merged before @sdroege's 
Travis just had internal error.

**Comment by sdroege** [comment]
Doesn't interfere with my PRs, or am I missing something?

**Comment by EPashkin** [comment]
Not much interference

**Comment by GuillaumeGomez** [comment]
Then I merge it.

**Pull request merged**
