### PR TITLE
Add gtk::PopoverConstraint and related Popover methods.

### PR DESCRIPTION
**Pull request by Susurrus**
Related to #426.

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Strange it wasn't generated before... Thanks!

@EPashkin: good for you as well?

**Comment by EPashkin** [comment]
@Susurrus, please, separate PR to 2 commit. First update gir and then "Regen"

**Comment by Susurrus** [comment]
Done.

**Comment by EPashkin** [comment]
Thanks. @GuillaumeGomez, 👍 after builds

**Comment by GuillaumeGomez** [comment]
Yes sir!

**Comment by EPashkin** [comment]
@GuillaumeGomez, it wasn't generated due it was added in 3.20 and on that update was too many changes. We simply missed new commented functions (69810fc7f65a)

**Comment by Susurrus** [comment]
It passed, anyone wanna merge?

**Pull request merged**
