### PR TITLE
Use the `glib_wrapper!` macro and wrap TreeIter

### PR DESCRIPTION
**Pull request by gkoz**
Requires https://github.com/gtk-rs/glib/pull/67

### CODE REVIEW

**Comment by gkoz** [comment]
It seems unlikely that all the methods really need `TreeIter` to be mutable but it's the GTK developers' call.

**Comment by GuillaumeGomez** [comment]
Well, I guess they have data that needs to be changed in order to have the status on read-only data... A bit weird but since I have no idea on how it works internally...

**Comment by gkoz** [comment]
Or they just didn't bother putting consts in the signatures because C isn't big on immutability.

**Comment by GuillaumeGomez** [comment]
Do they in the C++ binding ?

**Comment by gkoz** [comment]
It seems so. Compare https://github.com/GNOME/gtk/blob/master/gtk/gtktreemodel.h#L325-L326 and
 https://github.com/GNOME/gtkmm/blob/master/gtk/src/treemodel.hg#L186

**Comment by GuillaumeGomez** [comment]
Then let's do it as well. If it's autogenerated, can we set an exception for this case ?

**Comment by gkoz** [comment]
Okay.

We could add a way to assert constness in the gir config. Ideally we'd probably try to push the consts upstream.

**Comment by EPashkin** [comment]
Other variant do separate program that modified `c:type` in girs for listed cases.

**Comment by gkoz** [comment]
The `gi-rust` project seems to be going down the path of transforming the xmls before processing them.

Adding an generalized quirks section to the config should be possible though. Unifying the existing blacklisting and non-nullability settings in the process.

**Comment by gkoz** [comment]
Changed many `TreeIter` references back to immutable. Fixed more signatures I missed the last time. 

Added safety checks to `reorder`. There aren't any checks on the other side: [behold](https://github.com/GNOME/gtk/blob/master/gtk/gtktreestore.c#L2305-L2311).

**Comment by gkoz** [comment]
@GuillaumeGomez you're going to like https://github.com/gtk-rs/gtk/commit/46f3cf1dcb5de5706cfcd464aa3a6c7d3b8a6e3a, this will likely solve your process viewer crashes.

**Comment by GuillaumeGomez** [comment]
Oh yes ! Finally !

**Comment by gkoz** [comment]
All right, it's green!

**Pull request merged**
