### PR TITLE
Crate update

### PR DESCRIPTION
**Pull request by EPashkin**
Part of https://github.com/gtk-rs/examples/pull/284

@GuillaumeGomez Is better do minor version update in this PR or your script do that?

cc @sdroege

### CODE REVIEW

**Comment by sdroege** [comment]
> Switch from lazy_static to once_cell

This changes the API slightly (also the gir regen).

Please create a clean branch on top of the last release and only cherry-pick the commits you want to have included :)

**Comment by GuillaumeGomez** [comment]
For the version update, put it into master and then cherry-pick it as well. Also: please target the `0.8` branch instead. :)

**Comment by EPashkin** [comment]
Ok, I will do cherry pick without gir update on 0.8 branch

**Comment by EPashkin** [comment]
@GuillaumeGomez, @sdroege Can you create "0.12" branch on gdk, "0.8" on gio from "crate" ?

**Comment by GuillaumeGomez** [comment]
Oh sure! Normally it's done at every release but for some release it wasn't this done...

**Comment by GuillaumeGomez** [comment]
Done!

**Comment by sdroege** [comment]
:+1:

**Pull request merged**
