### PR TITLE
Added more CellRenderer subclasses: Text, Spinner, Progress, Toggle, Accel, Combo, Spin

### PR DESCRIPTION
**Pull request by hfiguiere**
This is on top the other PR #937

### CODE REVIEW

**Comment by sdroege** [comment]
@GuillaumeGomez Also this is green, please merge after #937

**Comment by GuillaumeGomez** [comment]
Restarting CI.

**Comment by hfiguiere** [comment]
rebases on master now.

**Comment by sdroege** [comment]
@GuillaumeGomez Please merge :)

**Comment by GuillaumeGomez** [comment]
Thanks!

**Pull request merged**
