### PR TITLE
Add renaming for WidgetExt::set_name and BuildableExt::set_name

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes https://github.com/gtk-rs/gtk/issues/914.

Bound to https://github.com/gtk-rs/gir/pull/873

### CODE REVIEW

**Comment by sdroege** [comment]
Also for `get_name` please :)

**Comment by GuillaumeGomez** [comment]
Oh right.

**Comment by sdroege** [comment]
:+1: once the gir change is in

**Comment by sdroege** [comment]
And regen and merge :) @GuillaumeGomez

**Comment by GuillaumeGomez** [comment]
Regen is already done. The examples are failing. :) Merging then!

**Pull request merged**
