### PR TITLE
Fix TargetList::new implementation

### LINKED ISSUE #621: Incorrect conversion of &[TargetEntry] in TargetList::new.
Currently each entry is converted to glib independently, and then address of
one of them is passed to gtk_target_list_new. See https://github.com/gtk-rs/gtk/blob/d3fb35605254f794c4cf669f49d0cdfe09dfc9dc/src/target_list.rs#L10 for details. It will crash when passed more than one TargetEntry.

On the other hand, implementation in https://github.com/gtk-rs/gtk/blob/1efdfd8d9a9bafcd0c4f5c87816bbecc3930a1eb/src/widget.rs#L53
appears to be doing the correct thing.

### PR DESCRIPTION
**Pull request by EPashkin**
Fix #621 

cc @GuillaumeGomez , @sdroege , @tmiasko

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Less code, seems like a good thing to me. :)

**Comment by sdroege** [comment]
:+1:

**Comment by EPashkin** [comment]
@sdroege There strange gio-related error on travis added in https://github.com/gtk-rs/gio/pull/78
```
error[E0433]: failed to resolve. Could not find `windows` in `os`
  --> /home/travis/.cargo/git/checkouts/gio-a4b825b310a073b9/37c2a08/src/socket.rs:18:14
   |
18 | use std::os::windows::io::{IntoRawSocket, FromRawSocket};
   |              ^^^^^^^ Could not find `windows` in `os`
```

**Comment by EPashkin** [comment]
Oh, it on doc building, gio don't have it so we missed.
Seems we need declare fake traits `IntoRawSocket, FromRawSocket` in case `dox` and not `windows`?

**Comment by GuillaumeGomez** [comment]
Maybe there's a way to make gir directly generate this as well?

**Comment by EPashkin** [comment]
cc @GuillaumeGomez as it doc related

**Comment by EPashkin** [comment]
Gir generated functions with wrong array type
```rust
impl TargetList {
    pub fn new(targets: &[&TargetEntry]) -> TargetList {
        assert_initialized_main_thread!();
        let ntargets = targets.len() as u32;
        unsafe {
            from_glib_full(ffi::gtk_target_list_new(targets.to_glib_none().0, ntargets))
        }
    }
```

**Comment by sdroege** [comment]
> Oh, it on doc building, gio don't have it so we missed.
Seems we need declare fake traits IntoRawSocket, FromRawSocket in case dox and not windows?

That seems annoying. I thought the point of dox was that it can build things for any platform

**Comment by GuillaumeGomez** [comment]
It should actually.

**Comment by EPashkin** [comment]
@GuillaumeGomez please restart travis here

**Comment by GuillaumeGomez** [comment]
Yes sir!

**Comment by EPashkin** [comment]
@GuillaumeGomez This ready for merge

**Comment by GuillaumeGomez** [comment]
Thanks!

**Pull request merged**
