### PR TITLE
Switch CI to build master branch of examples

### PR DESCRIPTION
**Pull request by EPashkin**

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Oh good point.

**Comment by EPashkin** [comment]
Second appveyor failed on loading rust installer, so I stopped it.

**Comment by EPashkin** [comment]
@GuillaumeGomez Please, restart CI here, just in case

**Comment by GuillaumeGomez** [comment]
Restarted.

**Comment by EPashkin** [comment]
Ok, CI passed, so it ready

**Comment by GuillaumeGomez** [comment]
Great, thanks!

**Pull request merged**
