### PR TITLE
WIP: Add runtime tests for properties

### PR DESCRIPTION
**Pull request by EPashkin**

### CODE REVIEW

**Comment by EPashkin** [comment]
Strange, why Ubuntu have not-debug gtk?
```
     Running target/debug/deps/child_properties-edc2f768f25df5d1

running 1 test

test child_properties ... FAILED

failures:

---- child_properties stdout ----

	thread 'child_properties' panicked at 'libgtk-3 was configured with `--enable-debug=no`. See https://github.com/gtk-rs/gtk/issues/270 for details', src/rt.rs:144

note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by EPashkin** [comment]
@GuillaumeGomez You don't have any idea why gtk don't run on travis?
I don't believe that Ubuntu have non debug build (we have many issues it this case)

**Comment by GuillaumeGomez** [comment]
Erf... Another strange issue. We'll maybe need to re-install gtk libraries ourselves...

**Comment by EPashkin** [comment]
Now we get warning `(child_properties-91eec81257b417af:2555): Gtk-WARNING **: cannot open display: `
with test failure.
I don't understand where it panic, but it seems reasonable :cry:

**Comment by GuillaumeGomez** [comment]
Ok, this time it's normal. Obviously, we don't have a display on these VMs so it *seems* normal.

**Comment by EPashkin** [comment]
@GuillaumeGomez, as runtime test on travis impossible I think that better close this PR even if it works on appveyor.
PS. On travis it produced strange "empty" warnings  https://travis-ci.org/gtk-rs/gtk/jobs/224753578#L367-L373

**Comment by GuillaumeGomez** [comment]
Keep it open. I can't promise anything but when I have enough time I'll try to understand what's wrong in here.

**Comment by GuillaumeGomez** [comment]
Hold on, it seems that it worked this time.

**Comment by EPashkin** [comment]
It because I enabled tests only for windows and it result those strange warnings on travis.

**Comment by EPashkin** [comment]
Moved to separate repository https://github.com/EPashkin/gtk-rs-runtime-tests

**Pull request closed without merging**
