### PR TITLE
Add check for 1.28

### PR DESCRIPTION
**Pull request by GuillaumeGomez**

### CODE REVIEW

**Comment by EPashkin** [comment]
@GuillaumeGomez Seems I missed something. Why you to do this?

**Comment by GuillaumeGomez** [comment]
If these files are useless, shouldn't we remove them?

**Comment by EPashkin** [comment]
This question about replace stable with 1.28  (while PR title says "add")

**Comment by GuillaumeGomez** [comment]
It's a discussion we had with @sdroege: gstreamer is supporting `1.28` (giving you context about all those PRs). But yes, it should be called "replace" instead. Replacing all titles (:sob:).

**Pull request merged**
