### PR TITLE
Use cache to speed up builds

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
The first commit will likely be slower but let's see after this one. :3

cc @EPashkin @sdroege

### CODE REVIEW

**Comment by EPashkin** [comment]
May be restart one of finished job to check how cache works?

**Comment by EPashkin** [comment]
Hm,  restarted job stalled on initializing cache.

**Comment by sdroege** [comment]
See what I wrote on IRC:

```
<slomo_> imperio: it can be easily slower in the future if you don't clean the cache often enough
<slomo_> imperio: the cache will become too huge :)
```

**Comment by GuillaumeGomez** [comment]
Might not be worth it then... Closing!

**Pull request closed without merging**
