### PR TITLE
Make the check_init_asserts script more robust and readable

### PR DESCRIPTION
**Pull request by gkoz**

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Great! Thanks a lot!

**Comment by gkoz** [comment]
The checks will still fail until https://github.com/gtk-rs/gir/pull/243 is used to regenerate. That could happen as part of #315 or here.

**Comment by EPashkin** [comment]
+1

**Comment by gkoz** [comment]
Spelled out macro names in the script fully.

**Comment by EPashkin** [comment]
AppVeyour done

**Pull request merged**
