### PR TITLE
Calculate lengths parameters

### PR DESCRIPTION
**Pull request by EPashkin**
Apply of https://github.com/gtk-rs/gir/pull/418
Closes https://github.com/gtk-rs/gtk/issues/477

### CODE REVIEW

**Comment by EPashkin** [comment]
cc @GuillaumeGomez , @sdroege Replaced manual functions with generated.
Only last it to add "gir submodule update"

cc @Susurrus too as it almost closes https://github.com/gtk-rs/gtk/issues/477

**Comment by GuillaumeGomez** [comment]
Seems good to me. Waiting for others'.

**Comment by sdroege** [comment]
Looks good

**Comment by EPashkin** [comment]
@GuillaumeGomez Updated to last gir, better merge this after or simultaneously with https://github.com/gtk-rs/examples/pull/139 or we have constant build failures

**Comment by GuillaumeGomez** [comment]
I'll just merge both at once. Thanks!

**Pull request merged**
