### PR TITLE
Add GLArea widget

### PR DESCRIPTION
**Pull request by gkoz**

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Well, it'll be faster this way. Thanks a lot for finishing it (still installing...) !

**Comment by gkoz** [comment]
@GuillaumeGomez if you enable "Rolling builds" in appveyor settings for each repo, building obsolete commits will stop automatically.

**Comment by GuillaumeGomez** [comment]
I'll add it then. Thanks for the tips. ^^

**Comment by gkoz** [comment]
I've encountered a good blog post explaining how GTK and GL are supposed to be used together: https://www.bassi.io/articles/2015/02/17/using-opengl-with-gtk/ Seems, you've only scratched the surface ;) Before this example can be implemented in Rust, some collaboration with the `glium/glutin` project may be needed.

**Comment by GuillaumeGomez** [comment]
I know the owner of glium. I'll ask him.

**Pull request merged**
