### PR TITLE
ignore all the deprecated objects

### PR DESCRIPTION
**Pull request by bilelmoussaoui**
I have been running `gir -c ./Gir.toml -d gir-files/ -m not_bound | grep "\[NOT GENERATED\]"` a lot today, tracking down missing stuff. This merge requests ignores every deprecated object before 3.14.

### CODE REVIEW

**Comment by sdroege** [comment]
Shouldn't we simply ignore them in `gir` directly if their deprecated version is before the minimum version and it is configured to remove deprecated things?

**Comment by GuillaumeGomez** [comment]
I agree with @sdroege's suggestion.

**Comment by bilelmoussaoui** [comment]
> Shouldn't we simply ignore them in `gir` directly if their deprecated version is before the minimum version and it is configured to remove deprecated things?

Well, sometimes the object (for example Gtk.VScrollbar) is only mentioned as deprecated on the object doc

**Comment by bilelmoussaoui** [comment]
Makes sense, I will keep this open until there's such an option on gir and update this one accordingly

**Pull request closed without merging**
