### PR TITLE
Add child properties to Grid

### PR DESCRIPTION
**Pull request by EPashkin**
Part of #392.

WIP
Published as testing place for int child properties.

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Both of our codes are exactly the same now. I guess we're good! :D

**Comment by EPashkin** [comment]
Not exactly: I use `Value::from` for initialize now, it will be changed when we make macros.

**Comment by EPashkin** [comment]
Added macro. As I not found way macroing function constraints it stay in `src/grid.rs`.
IMHO multiplicity of macro arguments not really needed.

**Comment by GuillaumeGomez** [comment]
I'm a bit worry about what the generated doc will look like on this... :-/

**Pull request merged**
