### PR TITLE
Automatic deprecation

### PR DESCRIPTION
**Pull request by EPashkin**
WIP.
Need "Gir submodule update" and "Regen"

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
So is it ok to get merged or not yet?

**Comment by EPashkin** [comment]
No it need final update after `gir` part merged

**Comment by GuillaumeGomez** [comment]
Ok, ping me once done then.

**Comment by EPashkin** [comment]
Ready to merge

**Comment by GuillaumeGomez** [comment]
Thanks!

**Pull request merged**
