### PR TITLE
Rename MenuExt trait to GtkMenuExt to avoid conflict with gio

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
cc @sdroege @EPashkin

### CODE REVIEW

**Comment by sdroege** [comment]
:+1:

**Comment by EPashkin** [comment]
👍 too

**Comment by GuillaumeGomez** [comment]
Why is `git diff -R` failing?

**Comment by EPashkin** [comment]
Diff passed https://travis-ci.org/gtk-rs/gtk/jobs/435577441#L755,
but manual code need fixed https://travis-ci.org/gtk-rs/gtk/jobs/435577442#L1730

**Comment by GuillaumeGomez** [comment]
I'll fix it just after merging this one then.

**Pull request merged**
