### PR TITLE
Add support for overriding Widget::draw() virtual method

### PR DESCRIPTION
**Pull request by sdroege**
CC @GuillaumeGomez @BrainBlasted

### CODE REVIEW

**Comment by EPashkin** [comment]
@sdroege Thanks, 👍

**Comment by GuillaumeGomez** [comment]
👍

**Comment by sdroege** [comment]
As green as it gets. @GuillaumeGomez please merge and then check the checkbox in https://github.com/gtk-rs/gtk/issues/862 for the `draw` vfunc :)

**Comment by GuillaumeGomez** [comment]
Thanks!

**Pull request merged**
