### PR TITLE
Add child properties for gtk::Notebook

### PR DESCRIPTION
**Pull request by antoyo**

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
@EPashkin: I have issues with duplicates in here but the fact is that at least we have a more unified API. So from this point of view, I *think* it's acceptable.

**Comment by EPashkin** [comment]
@antoyo There to many unneeded changes, please, regenerate it with Gir bf7bd49
As @GuillaumeGomez accept this and it compiles I accept despite objections in #495

**Comment by antoyo** [comment]
@EPashkin Actually, there are different git hashes in the repository, right now.
Look at these two files:
https://github.com/gtk-rs/gtk/blob/master/src/auto/about_dialog.rs
https://github.com/gtk-rs/gtk/blob/master/src/auto/app_chooser_dialog.rs
If I use the git hash you mentioned, there'll be more modifications.

**Comment by EPashkin** [comment]
If you build Git from commit bf7bd49f50755a8d1204a3d13b0e8a743a79f458
only 2 files changed: Gir.toml and src/auto/notebool.rs

**Comment by EPashkin** [comment]
On windows sometimes build.rs don't run and gir_version.rs don't changed. It can fixed with touching Cargo.toml. IMHO it not issue on linux
But anyway if you build with right Gir then will no other changes (with the exception of first 2 lines)

**Comment by EPashkin** [comment]
Also you can try do `make` in gtk root ;)

**Comment by antoyo** [comment]
I've fixed it.
By the way, if you don't want the users to use these new methods (for the reasons you mentioned), perhaps we could add `#[doc(hidden)]` on top of them.

**Comment by EPashkin** [comment]
Now I understand why there to many files changes: I do partial regen in #486 as we plan do full regen later.
I forgot that, sorry.
Please remove other files from commit

**Comment by EPashkin** [comment]
Currently no way adding #[doc(hidden)] but it was good idea

**Comment by GuillaumeGomez** [comment]
And could be quite easy to add.

**Comment by EPashkin** [comment]
Added gir issue.

**Comment by GuillaumeGomez** [comment]
Let's make the change in gir first and then please update your code in here @antoyo. :)

**Comment by EPashkin** [comment]
As do regen after to next version of gir will do too many changes IMHO better
Just add `doc_hidden=true` here in Gir.toml and merge this PR

**Comment by GuillaumeGomez** [comment]
@EPashkin: Good point.

@antoyo: Can you update please? :)

**Comment by EPashkin** [comment]
Too many hidden docs ;)
@antoyo Please unhide position and  tab-label as actually don't have equal direct function

**Comment by GuillaumeGomez** [comment]
I'll be out for a few hours. See you later!

**Comment by antoyo** [comment]
@EPashkin I believe the `tab-label` can already be set by [`set_tab_label_text`](http://gtk-rs.org/docs/gtk/struct.Notebook.html#method.set_tab_label_text) and `position` by [`reorder_child`](http://gtk-rs.org/docs/gtk/struct.Notebook.html#method.reorder_child).

**Comment by EPashkin** [comment]
@antoyo You right.
@GuillaumeGomez 👍 for merge

**Comment by GuillaumeGomez** [comment]
Thanks to both of you! :)

**Pull request merged**
