### PR TITLE
Regen

### PR DESCRIPTION
**Pull request by EPashkin**
Part of https://github.com/gtk-rs/gir/pull/490

cc @GuillaumeGomez, @sdroege

### CODE REVIEW

**Comment by sdroege** [comment]
👍

**Comment by EPashkin** [comment]
Strange all comands `exited with 0` but travis failed.

**Comment by EPashkin** [comment]
Oh, it `check_init_asserts` again

**Comment by EPashkin** [comment]
CI passed here

**Comment by GuillaumeGomez** [comment]
Thanks!

**Pull request merged**
