### PR TITLE
ShortcutLabel

### PR DESCRIPTION
**Pull request by jangernert**
follow up to #884

### CODE REVIEW

**Comment by EPashkin** [comment]
@jangernert Thanks, but CI will nags until submodule `gir-files` will not updated

**Comment by jangernert** [comment]
@EPashkin I'm not sure what you mean by that. Anything I still need to do? Or do we just have to wait until the CI bot has the newest commit of `gir-files` available to it?

**Comment by GuillaumeGomez** [comment]
There is no bot. You're supposed to update it. :)

**Comment by jangernert** [comment]
@GuillaumeGomez like this? Anything still missing?

**Comment by GuillaumeGomez** [comment]
I think you're done. Let's just wait for CI confirmation then we'll review.

**Comment by jangernert** [comment]
Ping

**Comment by GuillaumeGomez** [comment]
Looks good to me.

cc @EPashkin @sdroege

**Comment by EPashkin** [comment]
@jangernert Thanks
👍

**Comment by GuillaumeGomez** [comment]
Thanks @jangernert !

**Comment by jangernert** [comment]
Thanks @EPashkin @GuillaumeGomez @sdroege !

**Pull request merged**
