### PR TITLE
Add ImageMenuItem

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
cc @gkoz 
cc @EPashkin

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Before merging this, I need to add some manual doc to [lgpl-docs](https://github.com/gtk-rs/lgpl-docs) repository.

**Comment by EPashkin** [comment]
+1

**Comment by gkoz** [comment]
No need to wait for the lgpl-docs changes. It might even be easier to test the docs changes with this merged.

**Comment by GuillaumeGomez** [comment]
I let you handle it then. :)

**Pull request merged**
