### PR TITLE
Add Application and ApplicationWindow, add TreeView::get_selection quirk

### PR DESCRIPTION
**Pull request by gkoz**
The examples build will fail because of ca24ec0

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Thanks! Can you squash the two last commits please?

**Comment by gkoz** [comment]
Travis wants to update submodules by default. Interesting... I guess I'll have to merge the gir PR after all.

> Can you squash the two last commits please?

Any reason to do that? I'm not a fan of putting not exactly related changes in one commit.

**Comment by GuillaumeGomez** [comment]
The "update gir" and the "regen" ones could be only one. I don't see the point to have both of them.

**Comment by gkoz** [comment]
Regeneration follows three commits, each influencing the generated code.

**Comment by gkoz** [comment]
Updated. The examples build failure handled in https://github.com/gtk-rs/examples/pull/75

**Pull request merged**
