### PR TITLE
Fix more non-nullable returns

### PR DESCRIPTION
**Pull request by sophie-h**
Will leave this open for a while because I might stumble over some more

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Thanks!

**Comment by sdroege** [comment]
Let's get this and the corresponding changes to the examples in soonish?

**Comment by sophie-h** [comment]
> Let's get this and the corresponding changes to the examples in soonish?

There are no examples using those features. Rebased to let the tests pass.

**Comment by sdroege** [comment]
Thanks!

@GuillaumeGomez CI is green

**Pull request merged**
