### PR TITLE
Fix version for property FontChooser.level

### PR DESCRIPTION
**Pull request by EPashkin**
See comment https://github.com/gtk-rs/gtk/issues/794#issuecomment-483460392

cc @GuillaumeGomez, @sdroege , @martinber

Note not sure that it pass CI's regencheck as I don't updated sub-modules, so better wait for it.

### CODE REVIEW

**Comment by EPashkin** [comment]
Updated with versions for other 2 new properties

**Comment by EPashkin** [comment]
Reported bug to upstream https://gitlab.gnome.org/GNOME/gtk/issues/1830

**Comment by sdroege** [comment]
:+1: but why do tests fail?

**Comment by sdroege** [comment]
> but why do tests fail?

macos travis still broken (@GuillaumeGomez can we just disable that until someone fixes it?), 32 bit Windows still failing the tests for unknown reason.

**Comment by EPashkin** [comment]
Because we still can't solve problems with apveour32 and travis's OSX.
32bit has due some wrong lib, but I don't know how to find it, see https://github.com/gtk-rs/gtk/issues/783
For OSX need specialist on `brew` to disable removal (I can't find way) or travis rebuild its images with never version.

**Comment by GuillaumeGomez** [comment]
I'll work on the travis issue when I'm in Berlin. Meanwhile, just ignore it.

**Comment by EPashkin** [comment]
Rebased to master, travis passed too, @GuillaumeGomez thanks.

**Comment by GuillaumeGomez** [comment]
Thanks!

**Pull request merged**
