### PR TITLE
Readme: Fix doc link

### PR DESCRIPTION
**Pull request by Hofer-Julian**

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
The link is not invalid here. But I wonder if we should point directly to the doc pages. Not sure...

cc @sdroege @EPashkin

**Comment by Hofer-Julian** [comment]
> The link is not invalid here. But I wonder if we should point directly to the doc pages. Not sure...
> 
> cc @sdroege @EPashkin

Really? I get this when I click on it
grafik

**Comment by GuillaumeGomez** [comment]
Oh damn, you're right. The correct URL is: https://gtk-rs.org/docs-src/ Can you use this one instead please?

**Comment by Hofer-Julian** [comment]
Done :)

**Comment by GuillaumeGomez** [comment]
Thanks!

**Pull request merged**
