### PR TITLE
Add Popover Menu

### PR DESCRIPTION
**Pull request by PhnxRbrn**
This is my first attempt at a PR for this project, so hopefully I got everything correct for PopoverMenu for issue #149 .

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Hi ! Thanks a lot for the PR ! You just forgot to add the declaration of your C-cast function at the end of [/gtk-sys/src/lib.rs](https://raw.githubusercontent.com/gtk-rs/gtk/master/gtk-sys/src/lib.rs). Once you've added it, please squash your commits into one.

**Comment by GuillaumeGomez** [comment]
cc @gkoz

**Comment by gkoz** [comment]
To brag a little, here's how the generator (still a work in progress) currently does this: https://github.com/gkoz/gtk-rs-gtk/blob/object_reform_gir/src/auto/popover_menu.rs

And thanks to that I've noticed that this can't work because `gtk_popover_menu_new` doesn't take any arguments.

**Comment by PhnxRbrn** [comment]
Fixed new to note take any arguments

**Comment by GuillaumeGomez** [comment]
Perfect, thanks a lot ! I wait travis build result and then I merge.

**Pull request merged**
