### PR TITLE
Use correct transfer annotation for gtk_gl_area_new.

### PR DESCRIPTION
**Pull request by tmiasko**
This regen that applies changes from https://github.com/gtk-rs/gir-files/pull/19 and fixes issue #637.
The actual change is single word diff in src/auto/gl_area.rs.

### CODE REVIEW

**Comment by EPashkin** [comment]
@tmiasko Thanks.
@GuillaumeGomez 👍 for this too

**Comment by tmiasko** [comment]
Single word vs Files changed 208. It seems like we should start using single version file.

**Comment by EPashkin** [comment]
@tmiasko One month passed since https://github.com/gtk-rs/gio/pull/92, maybe it's time to add gtk as second test subject.
Want do it in this PR?

**Comment by tmiasko** [comment]
Yeah, lets do it here.

**Comment by EPashkin** [comment]
@tmiasko Thanks, now we have much more changes here.
@GuillaumeGomez 👍

**Comment by GuillaumeGomez** [comment]
Thanks!

**Pull request merged**
