### PR TITLE
Regen

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
cc @EPashkin

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
(there is no difference so I think we should just not merge this though)

**Comment by EPashkin** [comment]
Thanks

**Comment by EPashkin** [comment]
Agree that it can just merge without waiting CI

**Comment by GuillaumeGomez** [comment]
So we merge it even though nothing change?

**Comment by EPashkin** [comment]
If you want, but IMHO it unneeded,
so better just close PR or leave it for dox fixes

**Comment by GuillaumeGomez** [comment]
Then let's close it!

**Pull request closed without merging**
