### PR TITLE
Regen with GQuark

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
cc @sdroege @EPashkin

### CODE REVIEW

**Comment by EPashkin** [comment]
Gir need updated to generate `to_glib` for quarks,
I will do it today

**Comment by GuillaumeGomez** [comment]
@EPashkin: still:

```
   |
86 | from_glib(ffi::gtk_accel_group_activate(self.to_glib_none().0, accel_quark, acceleratable.to_glib_none().0, accel_key, accel_mods.to_glib()))
   |                                                                ^^^^^^^^^^^ expected u32, found struct `glib::Quark`
```

**Comment by GuillaumeGomez** [comment]
Ah damn, I need to regen I assume...

**Comment by GuillaumeGomez** [comment]
@EPashkin with the last gir version, shouldn't `.to_glib()` be generated on `GQuark` variables?

**Comment by EPashkin** [comment]
Version 3e102be generate `.to_glib()` for me:
```diff
--- a/src/auto/accel_group.rs
+++ b/src/auto/accel_group.rs
@@ -83,7 +83,7 @@ pub trait AccelGroupExt {
 impl<O: IsA<AccelGroup> + IsA<glib::object::Object>> AccelGroupExt for O {
     fn activate<P: IsA<glib::Object>>(&self, accel_quark: glib::Quark, acceleratable: &P, accel_key: u32, accel_mods: gdk::ModifierType) -> bool {
         unsafe {
-            from_glib(ffi::gtk_accel_group_activate(self.to_glib_none().0, accel_quark, acceleratable.to_glib_none().0, accel_key, accel_mods.to_glib()))
+            from_glib(ffi::gtk_accel_group_activate(self.to_glib_none().0, accel_quark.to_glib(), acceleratable.to_glib_none().0, accel_key, accel_mods.to_glib()))
         }
     }
```

**Comment by GuillaumeGomez** [comment]
I assume I failed my update then...

**Comment by EPashkin** [comment]
@GuillaumeGomez Thanks, 👍

**Pull request merged**
