### PR TITLE
Regenerate with latest GIR

### PR DESCRIPTION
**Pull request by sdroege**
See https://github.com/gtk-rs/gir/issues/508
and https://github.com/gtk-rs/gir/issues/509

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
So much lines for so few changes. :'(

:+1:

**Comment by sdroege** [comment]
Will be better (also in gdk-pixbuf) once @EPashkin stream changes for GIO are in. There are a couple of async functions on streams.

**Comment by GuillaumeGomez** [comment]
Which reminds me that my [sourceview PR](https://github.com/gtk-rs/sourceview/pull/31) hasn't been merged yet. I'll merge it and will let @EPashkin regen with stream.

**Comment by sdroege** [comment]
According to him the stream changes need a bit more work, more stuff missing

**Comment by sdroege** [comment]
CI is happy

**Comment by GuillaumeGomez** [comment]
Thanks!

**Comment by EPashkin** [comment]
@sdroege Thanks

**Pull request merged**
