### PR TITLE
Add SpinButtons::input signal

### PR DESCRIPTION
**Pull request by EPashkin**
WIP.
Currently only added not generated `input` signal.
Others can be just copy-pasted if it really needed.

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
You finally added the signals yourself? :p

**Comment by EPashkin** [comment]
Yes, but currently not added other 4 signals, can copy-paste and disable generation,
but not sure if it really needed.

**Comment by GuillaumeGomez** [comment]
If you don't do it, I'll, don't worry.

**Comment by GuillaumeGomez** [comment]
I'll merge it for now in order to complete it. It'll allow you to move forward on your other PR.

**Comment by EPashkin** [comment]
Bad, I waited gkoz's answers on example.
But we always can rework it.

**Comment by EPashkin** [comment]
Restart build for https://github.com/gtk-rs/examples/pull/86 please.

**Comment by GuillaumeGomez** [comment]
My bad. Well, generally I prefer that all the three of us have confirmed a PR before merging it but I thought you wanted to move forward on your other PR. My bad. (And I restarted builds).

**Pull request merged**
