### PR TITLE
Add support for subclassing GtkBin and GtkEventBox

### PR DESCRIPTION
**Pull request by BrainBlasted**

### CODE REVIEW

**Comment by sdroege** [comment]
:+1: Thanks!

**Comment by GuillaumeGomez** [comment]
Please rebase. Once done and when CI is happy, then I merge.

**Comment by BrainBlasted** [comment]
Rebased.

**Comment by BrainBlasted** [comment]
The CI failures don't seem to have anything to do with my changes.

**Comment by sdroege** [comment]
> The CI failures don't seem to have anything to do with my changes.

Yeah all creates need to be updated for an API change in glib :)

**Comment by sdroege** [comment]
@GuillaumeGomez Good to go

**Comment by GuillaumeGomez** [comment]
Yhanks!

**Pull request merged**
