### PR TITLE
WIP: test metadeps sys branch

### PR DESCRIPTION
**Pull request by gdesmott**
Not meant to be merged, I just want to have the CI running.

### CODE REVIEW

**Comment by gdesmott** [comment]
@sdroege @GuillaumeGomez : this was a build test using [my metadeps sys branch](https://github.com/gdesmott/sys/commit/d223e92396fa86f60ea48050fc675012694a41ad).

To my surprise all tests passed so I'm wondering what's the actual use case for all the current `build.rs` hacks: `GTK_INCLUDE_DIR`, `GTK_LIB_DIR`, windows specific paths, etc?

**Comment by sdroege** [comment]
Maybe they're not even required anymore and are just cargo culted for future generations. @EPashkin would know.

But as I said on IRC, we should really get rid of those hacks and instead set up the Windows CI environment correctly. Which might've happened by now (maybe msys2 fixed their packages...).

**Comment by EPashkin** [comment]
I tested on Windows with last msys2x64 and seems `hardcode_shared_libs` branches in good pkgconfig case now not needed (I not remember why it was added).
But IMHO we still better have GTK_LIB_DIR and fallback.
Not sure about `GTK_INCLUDE_DIR`

**Comment by sdroege** [comment]
> But IMHO we still better have GTK_LIB_DIR and fallback.
> Not sure about `GTK_INCLUDE_DIR`

The fallback is provided by metadeps in this branch, which allows to override things in a generic way for each dependency so that people can continue to work around their broken environments.

**Comment by EPashkin** [comment]
> The fallback is provided by metadeps in this branch, which allows to override things in a generic way for each dependency so that people can continue to work around their broken environments.

I don't see fallback not in sys branch not in https://github.com/gdesmott/metadeps/blob/master/src/lib.rs

**Comment by gdesmott** [comment]
It's all in my [wip branch](https://github.com/gdesmott/metadeps/blob/wip/src/lib.rs) for now.

**Comment by EPashkin** [comment]
I missed that it have branch, but IMHO it still don't have "similar" failure case  https://github.com/gdesmott/metadeps/blob/wip/src/lib.rs#L310

**Comment by gdesmott** [comment]
What do you mean? This feature is meant for crates building internally the underlying C library to statically link to it. That's not something we currently support in `gtk-rs`.

**Comment by EPashkin** [comment]
Yes, that why I say that you sys'es needed special fallback for this errors.

**Comment by gdesmott** [comment]
How so? metadeps will [raise an error](https://github.com/gdesmott/metadeps/blob/wip/src/lib.rs#L343) if user tries to use this feature as our sys don't implement a build closure.

**Comment by EPashkin** [comment]
> 
> 
> How so? metadeps will [raise an error](https://github.com/gdesmott/metadeps/blob/wip/src/lib.rs#L343) if user tries to use this feature as our sys don't implement a build closure.

And pkgconfig error is lost and we can't find it by metadeps error.

**Comment by gdesmott** [comment]
But that only happens if user explicitly defined `METADEPS_GTK_BUILD_INTERNAL=auto` or `always`. The default value is `never` so `metadeps` will fail on pkg-config and report its error.

**Comment by EPashkin** [comment]
Sorry, I seems totally go to wrong direction.
So we just need don't forget to add it in your sys'es.

**Comment by sdroege** [comment]
>  So we just need don't forget to add it in your sys'es.

Add what?

**Comment by EPashkin** [comment]
https://github.com/gtk-rs/sys/blob/master/gtk-sys/build.rs#L100-L106

**Comment by sdroege** [comment]
That's something for metadeps to take care of. The goal here is to move away from all these custom hacks that work differently for every crate.

Also the above part you linked shouldn't be done unconditionally as that regularly causes problems for users, especially on Windows. It needs to be something to opt-in for the user, which is already possible with metadeps by setting the correct libraries for the corresponding crate.

**Comment by sdroege** [comment]
This was merged

**Pull request closed without merging**
