### PR TITLE
Derive Default for builders

### PR DESCRIPTION
**Pull request by EPashkin**
Possible replacement for #905.

cc @antoyo

### CODE REVIEW

**Comment by EPashkin** [comment]
CI pass with just Derive (modulo regen_check).
As I remember @antoyo want derive Clone too, so I try to add it too.
PS. Was in wrong PR 😉

**Comment by EPashkin** [comment]
Seems CI like derive Clone too.
@antoyo You prefer with Clone or just derive Default?

**Comment by antoyo** [comment]
@EPashkin: Both.

**Comment by EPashkin** [comment]
Updated

**Comment by EPashkin** [comment]
CI passed

**Comment by GuillaumeGomez** [comment]
Thanks!

**Pull request merged**
