### PR TITLE
get_child_at function for Grid

### PR DESCRIPTION
**Pull request by LordSentox**
The function was missing, so I added it.

### CODE REVIEW

**Comment by gkoz** [comment]
Thank you for contributing!

Unfortunately the wrappers used in this branch can't handle checking the actual type of the widget so either the function has to be marked `unsafe` or return `Option<Widget>`. The branch, that would support downcasting properly, is under development.

**Comment by gkoz** [comment]
I think I'll go and mark the existing similar occurrences `unsafe`, making this one `unsafe` would be consistent with that.

**Comment by LordSentox** [comment]
I see. I was confused for a second, because I had modeled this function after the get_child function of bin, which was not marked unsafe.
Should I mark the function unsafe then, or would you prefer it to be in your commit, when you change the other functions alongside with it?

**Comment by gkoz** [comment]
I'd prefer you changed it but let's see what @GuillaumeGomez of the overall plan.

**Comment by GuillaumeGomez** [comment]
Hi @LordSentox, thanks for PR ! Like @gkoz said, I'd prefer you to set the function as `unsafe`. It's a temporary state, but I'd prefer it this way now.

**Comment by gkoz** [comment]
The better way to remove that commit would be by doing an interactive rebase.

Don't bother with handling lists and stuff unless you require a particular function. Most of it has been solved, just has to make its way into this branch.

**Pull request merged**
