### PR TITLE
Into option str

### PR DESCRIPTION
**Pull request by GuillaumeGomez**

### CODE REVIEW

**Comment by EPashkin** [comment]
By way, no "Update gir submodule" here?

**Comment by GuillaumeGomez** [comment]
Oups forgot, thanks for the reminder!

**Comment by GuillaumeGomez** [comment]
Are the examples built from this PR or from master?

**Comment by GuillaumeGomez** [comment]
Well, they seem to work so nevermind.

**Comment by GuillaumeGomez** [comment]
Tests passed. Is it ok for you @EPashkin?

**Comment by EPashkin** [comment]
Yes.

**Comment by GuillaumeGomez** [comment]
Great!

**Comment by Susurrus** [comment]
Excellent, thanks @GuillaumeGomez! I just tested this out with my code and everything builds and runs as I'd expect. Looks a lot cleaner now too.

**Comment by GuillaumeGomez** [comment]
Great! :)

**Pull request merged**
