### PR TITLE
Gdk update

### PR DESCRIPTION
**Pull request by Susurrus**
This enables all types that were added in gtk-rs/gdk#144

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
👍 

cc @EPashkin

**Comment by EPashkin** [comment]
👍  
@Susurrus Thanks

**Comment by Susurrus** [comment]
One thing I meant to note when I first posted that was that I don't know why `gdk::Atom` is still ignored for generating functions. There are still about 25 functions that only depend on `Gdk::Atom` and were not generated. Is there something I'm missing for that?

**Comment by EPashkin** [comment]
I don't remember reason but seems need to add both "Gdk.Atom" and  "Gdk.Atom_" to deignore it
and to gdk too.

**Pull request merged**
