### PR TITLE
Inhibit

### PR DESCRIPTION
**Pull request by EPashkin**
Part of https://github.com/gtk-rs/gir/issues/244

WIP

### CODE REVIEW

**Comment by EPashkin** [comment]
Ready for review but not for merge

**Comment by EPashkin** [comment]
Seems all current `widget` signals also can be generated, but I prefer don't do it in this PR

**Comment by EPashkin** [comment]
Regenerated with last `gir`.

**Comment by gkoz** [comment]
:+1:

**Comment by GuillaumeGomez** [comment]
Great! Thanks a lot!

**Comment by EPashkin** [comment]
@gkoz I started generating signals for `Widget` but stopped on `can-activate-accel` it has `u64` param instead `u32` from girs. It normal?

**Comment by gkoz** [comment]
@EPashkin looks like a mistake: it's `guint` in the code and gir.

**Comment by gkoz** [comment]
This seems like a pretty low-level API, we don't work with signal ids anywhere (a signal id is returned by `g_signal_new` not `g_signal_connect`).

**Pull request merged**
