### PR TITLE
Fix internal panic on Image::get_icon_image for images without names

### PR DESCRIPTION
**Pull request by EPashkin**
Ex. created from file

Solves problem in https://github.com/gtk-rs/gir/issues/350#issuecomment-326783065

cc @GuillaumeGomez, @sdroege

### CODE REVIEW

**Comment by EPashkin** [comment]
As properties generated and works fine and `get_property_icon_size` also works,
then maybe manual part unneeded?

**Comment by sdroege** [comment]
👍

**Comment by EPashkin** [comment]
@sdroege you vote for merge as is or remove manual part?

**Comment by GuillaumeGomez** [comment]
I'm all for removing the manual part if unneeded.

**Comment by sdroege** [comment]
Either way seems fine to me

**Comment by EPashkin** [comment]
Updated

**Comment by EPashkin** [comment]
CI passed

**Comment by GuillaumeGomez** [comment]
Thanks!

**Pull request merged**
