### PR TITLE
Remove xx_sys to xx_ffi renaming

### PR DESCRIPTION
**Pull request by EPashkin**
Part of https://github.com/gtk-rs/gir/issues/685

cc @GuillaumeGomez, @sdroege

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
👍

**Comment by sdroege** [comment]
:+1:

**Comment by EPashkin** [comment]
This is ready for merge if no problem with travis CI (appveyor 32 will fail again).

**Comment by EPashkin** [comment]
Brew again do mass remove, trying to fix

**Comment by EPashkin** [comment]
Very strange, `brew` think that libffi installed even after it deleted it.
```
$ if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew cleanup; fi
Removing: /Users/travis/Library/Caches/Homebrew/libffi-3.2.1.high_sierra.bottle.tar.gz... (97.2KB)
...
Removing: /Users/travis/Library/Logs/Homebrew/libffi... (68B)
...
$ if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gtk+3 cairo atk libffi; fi
Warning: libffi 3.2.1 is already installed and up-to-date
To reinstall 3.2.1, run `brew reinstall libffi`
```
Anyone have any idea?

**Comment by EPashkin** [comment]
Rebased to solve merge conflict

**Comment by GuillaumeGomez** [comment]
Then I merge. Thanks!

**Pull request merged**
