### PR TITLE
Run regen check when building for 3.14

### PR DESCRIPTION
**Pull request by sdroege**

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
:+1:

**Comment by sdroege** [comment]
All green apart from the known problem with GTK tests on 32 bit appveyor.

**Comment by GuillaumeGomez** [comment]
Any idea what's going on in appveyor test @EPashkin ?

**Comment by sdroege** [comment]
> Any idea what's going on in appveyor test @EPashkin ?

Yes, we discussed that before: https://github.com/gtk-rs/gtk/pull/779#issuecomment-462127159 and following comments. The CI environment is broken.

**Comment by sdroege** [comment]
Let's get this in until someone can look at the windows problems then?

**Comment by GuillaumeGomez** [comment]
Let's do it like this... Can you take a look at it when you have time please @EPashkin ? :)

**Pull request merged**
