### PR TITLE
Replace functions for RadioButton and RadioMenuItem

### PR DESCRIPTION
**Pull request by EPashkin**
Closes https://github.com/gtk-rs/gtk/issues/488
Using tests:
https://github.com/EPashkin/gtk-rs-runtime-tests/blob/radiobutton/tests/radio_button.rs
https://github.com/EPashkin/gtk-rs-runtime-tests/blob/radiobutton/tests/radio_menu_item.rs
cc @GuillaumeGomez, @sdroege

### CODE REVIEW

**Comment by EPashkin** [comment]
@GuillaumeGomez, @sdroege please check it.

**Comment by GuillaumeGomez** [comment]
Seems good for me, however I never used the radio groups so I'd prefer to rely on @sdroege on this.

**Comment by sdroege** [comment]
_I never used the radio groups API either, at least not in the last 10 years, and don't really work with GTK_

This looks good to me and should work fine, however it seems potentially confusing to users as the normal constructors now don't provide a way to define a group and you have to use the ones with `_widget` instead. Maybe implement that ones with the GSList group manually, so that the actual GSList is passed there and not a NULL pointer?

**Comment by EPashkin** [comment]
Problem with GSList changed on every `g_slist_prepend` so it almost impossible make it actual when it changed in C side

**Comment by sdroege** [comment]
I was thinking of just getting the GSList* from one of the buttons in the list (the first I guess?), probably making sure that all of the buttons in the list are in the same group (or maybe not?), and then passing it to the constructor.

**Comment by EPashkin** [comment]
Then we need ensure that user don't use list after it, or we again have wrong list (need change to consume group parameter).
I don't see it really more usable
```
let rd1 = new_with_label(None, "a");
let gr = rd1.get_group();
let rd2 = new_with_label(gr, "b");
let gr = rd2.get_group();
let rd3 = new_with_label(gr, "c");
```
that realized in this PR
```
let rd1 = new_with_label("a");
let rd2 = new_with_label("b");
let rd3 = new_with_label("c");
rd2.join_group(&rd1);
rd3.join_group(&rd1);
```

**Comment by sdroege** [comment]
I was thinking of never passing the GSList* to the user, but using it internally in the constructor, e.g.

```Rust
    pub fn new(group: &[RadioMenuItem]) -> RadioMenuItem {
        assert_initialized_main_thread!();
        unsafe {
            let c_group = ffi::gtk_radio_menu_item_get_group(to_glib_none(group[0])); // check if there is actually group[0] or if it's empty
            // possibly: check if all in group have the same group, or make it so
            Widget::from_glib_none(ffi::gtk_radio_menu_item_new(c_group)).downcast_unchecked()
        }
    }
```

But I missed the `join_group` API, I guess it's sufficient like that then :)

**Comment by EPashkin** [comment]
Hm. this way also doable (but need some checks for empty list). I add it to issue.

**Comment by EPashkin** [comment]
@sdroege You agree to merge PR as is?
IMHO arrayed version while doable, confuses the user: usage `&[]` for first member, need collect members to array or use `&[firstmember]` to adding.

**Comment by EPashkin** [comment]
Ping

**Comment by sdroege** [comment]
Fine with me, yes

**Comment by GuillaumeGomez** [comment]
Good for me too. Thanks!

**Pull request merged**
