### PR TITLE
Format code with rustfmt

### PR DESCRIPTION
**Pull request by sdroege**
Should be merged after https://github.com/gtk-rs/gtk/pull/826 and will need to be updated then.

### CODE REVIEW

**Comment by sdroege** [comment]
@GuillaumeGomez green apart from examples

The other PR needs to be completely updated anyway, so no problem merging this now already.

**Comment by GuillaumeGomez** [comment]
Indeed, let's merge!

**Comment by sdroege** [comment]
@GuillaumeGomez Now it should be fine again, merge conflicts solved

**Comment by GuillaumeGomez** [comment]
`TryFrom` isn't stable in 1.31?

**Comment by sdroege** [comment]
> `TryFrom` isn't stable in 1.31?

No, 1.34. Which is the minimum version I'm using in GStreamer now.

**Comment by sdroege** [comment]
@GuillaumeGomez This one is good to go apart from unrelated failures.

**Pull request merged**
