### PR TITLE
Regenerate with latest gir, rename ApplicationExt to GtkApplicationEx…

### PR DESCRIPTION
**Pull request by sdroege**
…t and ignore clippy warnings in generated code

### CODE REVIEW

**Comment by sdroege** [comment]
There are lots of clippy warnings in the manual code, but I don't have time to go through these now

**Comment by GuillaumeGomez** [comment]
I'll write a patch for them in gir I think. Is it ok for you @EPashkin?

**Comment by EPashkin** [comment]
> I'll write a patch for them in gir I think.

@sdroege You planning update gir to fix clippy warnings in manual code?

**Comment by EPashkin** [comment]
Sorry, I misread sender, question meant for @GuillaumeGomez

**Comment by GuillaumeGomez** [comment]
Aren't the clippy warnings for the generated code?

**Comment by sdroege** [comment]
The ones for the generated code are all gone after you merged this PR. Only the ones in the manual code are left afterwards.

**Comment by GuillaumeGomez** [comment]
Ah I see. Well, I'll fix them this evening then. Thanks!

**Pull request merged**
