### PR TITLE
Add missing child properties for Box

### PR DESCRIPTION
**Pull request by antoyo**
The example will follow soon as a pull request of the examples repository.

### CODE REVIEW

**Comment by EPashkin** [comment]
Box already has [set_child_packing](https://github.com/gtk-rs/gtk/blob/master/src/auto/box_.rs#L60) and [query_child_packing](https://github.com/gtk-rs/gtk/blob/master/src/auto/box_.rs#L50) so IMHO this properties unneeded.

**Comment by antoyo** [comment]
The reason why I added these is that I created a crate called [`relm`](https://github.com/antoyo/relm) and this allows to set child properties individually like [in this example](https://github.com/antoyo/relm/blob/master/examples/buttons-child-attribute.rs#L89-L95).
This code generates the call to `set_child_fill` for instance.

**Comment by EPashkin** [comment]
Ok, then I don't against adding these

**Comment by EPashkin** [comment]
But rebuild it with Gir b7f5189 or add update gir submodule here

**Comment by antoyo** [comment]
I regenerated with this revision.

**Comment by GuillaumeGomez** [comment]
Thanks a lot!

**Pull request merged**
