### PR TITLE
Port to futures 0.3

### PR DESCRIPTION
**Pull request by sdroege**
While this requires nightly, the API is now stabilized and will become part of Rust 1.36. IMHO we should merge this now so that it can all get wider testing.

### CODE REVIEW

**Comment by sdroege** [comment]
This is currently marked as WIP because it uses https://github.com/gtk-rs/glib/pull/476 and https://github.com/gtk-rs/gir/pull/753 via Cargo patching

**Comment by sdroege** [comment]
This should also be ready now

**Comment by GuillaumeGomez** [comment]
Waiting for CI as well. :)

**Comment by sdroege** [comment]
@GuillaumeGomez green

**Comment by GuillaumeGomez** [comment]
Thanks!

**Pull request merged**
