### PR TITLE
Change gtk::Application::new parameter to use Into<Option<&str>>

### PR DESCRIPTION
**Pull request by jeandudey**

### CODE REVIEW

**Comment by EPashkin** [comment]
Thanks, can you do same for others in `src` (dialog, entry_buffer, etc.) ?

**Comment by GuillaumeGomez** [comment]
@EPashkin: slow down, don't scare newcomers! :p
@jeandudey: you forgot to add the lifetime:

```rust
 fn new<I: Into<Option<&str>>>(application_id: I, flags: ApplicationFlags) -> Result<Application, glib::BoolError> {
// should be:
 fn new<'a, I: Into<Option<&'a str>>>(application_id: I, flags: ApplicationFlags) -> Result<Application, glib::BoolError> {
```

**Comment by EPashkin** [comment]
Also we missed it on previous PR but both function need `pub`

**Comment by GuillaumeGomez** [comment]
Oh damn indeed!

**Comment by jeandudey** [comment]
@GuillaumeGomez i fixed it and made the functions there public.

**Comment by GuillaumeGomez** [comment]
Thanks!

**Comment by Susurrus** [comment]
Was there a reason the `Into<Option<&str>>` was skipped for the pre-3.6 version of `Application::new()`?

**Comment by GuillaumeGomez** [comment]
It's because it wasn't generated automatically.

**Comment by Susurrus** [comment]
No, I mean there are two `Application::new()` functions. Only 1 was "fixed" in this PR to support the `Into<Option<&str>>`. Was there a reason the second one wasn't updated as well?

**Comment by EPashkin** [comment]
May be because `application_id` is non-optional ;)

**Comment by GuillaumeGomez** [comment]
The other one isn't an `Option<&str>` so why would it need the `Into`?

**Comment by Susurrus** [comment]
You're right, sorry about that!

**Pull request merged**
