### PR TITLE
Make TextIter a wrapper around glib::boxed::Boxed

### PR DESCRIPTION
**Pull request by gkoz**
Relies on https://github.com/gtk-rs/glib/pull/63

### CODE REVIEW

**Comment by gkoz** [comment]
cc @EPashkin, the design of the wrapper and conversions impacts the generator obviously.

**Comment by EPashkin** [comment]
@gkoz No problem

**Comment by gkoz** [comment]
The glob import bug strikes again :(

**Comment by gkoz** [comment]
@GuillaumeGomez this is ready now.

**Comment by GuillaumeGomez** [comment]
Thanks !

**Pull request merged**
