### PR TITLE
Tree sortable ignore get sort column

### PR DESCRIPTION
**Pull request by EPashkin**
@GuillaumeGomez, I just don't remember why get was not ignored.
May be it was some reason (backward compatibility etc.)?

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
I don't remember at all why it was bound in the first place. Whatever, once tests passed, I merge.

**Comment by EPashkin** [comment]
Enum `SortColumn` was added to manual part to separate -1 and other column numbers

**Comment by EPashkin** [comment]
.., so manual part use enum, not i32 https://github.com/gtk-rs/gtk/blob/master/src/tree_sortable.rs#L86

**Comment by GuillaumeGomez** [comment]
Oh I see. Makes sense.

**Comment by GuillaumeGomez** [comment]
Thanks!

**Pull request merged**
