### PR TITLE
Add ListBox::bind_model() and other functions taking closures

### PR DESCRIPTION
**Pull request by sdroege**
This is currently WIP, I'd like to add the other commented out functions too but it's becoming repetitous. Should probably do https://github.com/gtk-rs/gir/issues/618 first.

Any comments so far?

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Nope, seems good to me. Or at least didn't see any outstanding issue.

**Comment by EPashkin** [comment]
Looks good, I little worried about the lack of boxing, but I trust you

**Comment by sdroege** [comment]
> Looks good, I little worried about the lack of boxing, but I trust you

It's the same as boxing twice, just that we store it on the stack instead. The first reference taken creates a trait object (two pointers, the struct pointer and the vtable), the second reference is a single pointer to that trait object (and if it was more than a single pointer, the cast to `gpointer` would fail to compile).

**Comment by sdroege** [comment]
Should we get this in for now until the gir changes are done (probably going to take a few weeks :) )?

**Comment by GuillaumeGomez** [comment]
Sounds fine to me. Thanks! :)

**Pull request merged**
