### PR TITLE
Trampoline namespaces

### PR DESCRIPTION
**Pull request by EPashkin**
Example of https://github.com/gtk-rs/gir/issues/239 and https://github.com/gtk-rs/gir/issues/241 fixing
WIP as need sub-module gir update.

### CODE REVIEW

**Comment by EPashkin** [comment]
Gir's PR will be today, it need some refactoring.

**Comment by EPashkin** [comment]
@gkoz, seems we need generate cairo's records (`RectangleInt` at minimum)

**Comment by gkoz** [comment]
It appears the ffi type `GdkRectangle` is not an alias so on the ffi side there shouldn't be any ties to `cairo_rectangle_int_t` and on the rust side we have many options.

**Comment by EPashkin** [comment]
It alias
```xml
    <alias name="Rectangle" c:type="GdkRectangle">
      <doc xml:space="preserve">Defines the position and size of a rectangle. It is identical to
#cairo_rectangle_int_t.</doc>
      <type name="cairo.RectangleInt" c:type="cairo_rectangle_int_t"/>
    </alias>

```

**Comment by gkoz** [comment]
Curious. It is an alias in the gir-files we use but the newer versions [make it a record](https://github.com/gtk-rs/gir-files/compare/fedora-23?expand=1#diff-02a6c2f3428e9a1948046d1c1e4fa4c6R17581):
```xml
<record name="Rectangle"
            c:type="GdkRectangle"
            glib:type-name="GdkRectangle"
            glib:get-type="gdk_rectangle_get_type"
            c:symbol-prefix="rectangle">
      <doc xml:space="preserve">Defines the position and size of a rectangle. It is identical to
#cairo_rectangle_int_t.</doc>
```

**Comment by gkoz** [comment]
From looking at the build error in `add-editable` we just need a `FromGlibPtr` implementation for `RectangleInt`?

**Comment by EPashkin** [comment]
Yes.
I update last commit to use 'f: glib_ffi::gpointer`

**Comment by EPashkin** [comment]
Oops, I enabled `add-editable` only on my computer and added it to commit by error.
Fixed it.

**Comment by EPashkin** [comment]
@gkoz If you add `FromGlibPtr` to `cairo` before this merge, I enable `add-editable` here.
Any way you or @GuillaumeGomez need to merge https://github.com/gtk-rs/gir/pull/254 first.

**Comment by EPashkin** [comment]
Updated

**Comment by gkoz** [comment]
Oh great, converting `RectangleInt` means some shuffling in gdk...

**Comment by gkoz** [comment]
That's https://github.com/gtk-rs/gdk/pull/117 and https://github.com/gtk-rs/cairo/pull/76

**Comment by EPashkin** [comment]
I deignored `add-editable`
Thanks, @gkoz.

**Comment by EPashkin** [comment]
I confirmed that this PR will builds with gkoz's PR

**Comment by EPashkin** [comment]
Ready for merge after build recheck.

**Comment by EPashkin** [comment]
My bad, missed that https://github.com/gtk-rs/gdk/pull/117 still not merged.

**Comment by EPashkin** [comment]
Add ignoring signals for `CellArea` as it has manual part due `TreePath` parameters.
Marked all #manual ignores, added reason for it.

**Comment by EPashkin** [comment]
Include fix for https://github.com/gtk-rs/gir/issues/241

**Comment by EPashkin** [comment]
Ready for review and merge.

**Comment by GuillaumeGomez** [comment]
All good for me. Thanks @EPashkin!

**Pull request merged**
