### PR TITLE
Regen

### PR DESCRIPTION
**Pull request by GuillaumeGomez**

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Just waiting for your confirmation on this @EPashkin. :)

**Comment by EPashkin** [comment]
👍

**Comment by EPashkin** [comment]
Seems check_init_asserts need upgrade :(

**Comment by GuillaumeGomez** [comment]
That's what I was about to say haha.

**Comment by GuillaumeGomez** [comment]
Doing it.

**Comment by EPashkin** [comment]
Or Gir to add `assert_initialized_main_thread` at first line

**Comment by GuillaumeGomez** [comment]
Hum, I think it'll be better to do it in gir directly. Want to do it or do you prefer that I do it?

**Comment by EPashkin** [comment]
I still off for hour or three ;)

**Comment by GuillaumeGomez** [comment]
Doing it then! :D

**Comment by GuillaumeGomez** [comment]
Updated.

**Comment by EPashkin** [comment]
👍 Thanks

**Pull request merged**
