### PR TITLE
Update crates.io version

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
The final one! (Except if I forgot one...)

### CODE REVIEW

**Comment by EPashkin** [comment]
👍 Thanks
Seems nothing missed, it was better seen is there was tracking issue

**Comment by GuillaumeGomez** [comment]
Didn't think of it. Next time, let's do this. Thanks for your reviews. Merge time has come!

**Comment by EPashkin** [comment]
Missed, Examples and probably Test

**Comment by GuillaumeGomez** [comment]
For both of them, I need to push to crates.io (which is currently being done).

**Comment by EPashkin** [comment]
This and gdk don't builds with
```
error: found an override with a non-locked list
```

**Comment by EPashkin** [comment]
gdk-pixbuf-sys better update bitflags = "0.4" (it not related to prev error)

**Comment by GuillaumeGomez** [comment]
It builds fine for me. :-/

**Comment by EPashkin** [comment]
You also use .cargo/config ?

**Comment by GuillaumeGomez** [comment]
I just run `cargo build` so I guess not.

**Comment by EPashkin** [comment]
You right without .cairo/config gdk and gtk builds,

**Comment by GuillaumeGomez** [comment]
Great, I continue then!

**Comment by EPashkin** [comment]
Before publish may be update bitflags?

**Comment by EPashkin** [comment]
It has many places

**Comment by GuillaumeGomez** [comment]
The issue is that I already published "-sys" crates. Does this new version brings this much? :-/

**Comment by EPashkin** [comment]
Not problem, just gdk has v5 so currenly always 2 bitflags

**Comment by GuillaumeGomez** [comment]
Then we'll wait next update for changing this version. Sorry about that.

**Comment by EPashkin** [comment]
We can do it after publishing, so have time to test it ;)

**Comment by GuillaumeGomez** [comment]
Indeed, I prefer avoid rushing.

**Comment by GuillaumeGomez** [comment]
Ok, now I'm going to update the two remaining repositories. Do you mind writing the blog post announcing the new gtk version please? :)

**Comment by EPashkin** [comment]
Sorry, I'm very bad on writing posts (newer write one).

**Comment by GuillaumeGomez** [comment]
Just write a changelog then please, I don't know what has been added since last version. :-/

Also, examples repo doesn't seem to need to be updated. Looking to tests now.

**Comment by EPashkin** [comment]
About change log, seems we forgot tag releases but seems previus was in fe143389eedff019cfda70ed4ba3e2e30cac2b80

**Comment by EPashkin** [comment]
I try look for changes

**Comment by GuillaumeGomez** [comment]
Thanks! Meanwhile I'm fixing travis.

**Comment by EPashkin** [comment]
"Complete" changelog
All packages: update to gtk3.22 
Sys(from 774929a264759e2dd358ffc491889b25e0615cf9):
Cairo(from 831e363d738e7331a4b336dd5e175b8db8ea40c3):
Added optional xlib function
Added RadialGradient
Pango(from bb0a042378b4c60ce54f308f4405a7584a6fb1d7):
Gdk-pixbuf(759474e6ee26e3d4cc5840cacef55c1d4c95a04a):
Glib(11c384088f76e35317293971d9bbb6fb0b5af426):
Added signal_stop_emission and signal_stop_emission_by_name
Added signal_handler_block and signal_handler_unblock
Added KeyFile
Moved from Gtk signal Inhibit
Gio(7f5e21d538dc90dd2abed7364c8e8fd06a1ee799)
Changed return type for connect_writable_change_event to Inhibit
Gdk(from 5958e35f532b9a21a8b50ec3861bd531ef62e307)
Make enum unconvertable to i32 without to_glib and from_glib
Gtk(from fe143389eedff019cfda70ed4ba3e2e30cac2b80): 
Added FileChooserButton
Provide gtk::MessageDialog manual setter for secondary markup and text
Gir(from 222bcd33d9ba1ac2fd5f76c3abf5d829daeb1b0c)
Added nullable override for signals (parameters and returns)
Added nullable override for constructors

**Comment by EPashkin** [comment]
Missed changes
Glib:
Added utility functions get_application_name, get_program_name, get_environ, ...
Gdk:
Renamed struct Attributes to WindowAttr

**Comment by GuillaumeGomez** [comment]
Good! I'll write the blog post then.

**Pull request merged**
