### PR TITLE
Gir files zesty

### PR DESCRIPTION
**Pull request by EPashkin**
Part of https://github.com/gtk-rs/gir-files/issues/1

Closes https://github.com/gtk-rs/gtk/issues/403

### CODE REVIEW

**Comment by EPashkin** [comment]
Restart this after merge gdk, pls.

**Comment by GuillaumeGomez** [comment]
Restarted.

**Comment by EPashkin** [comment]
Good, it ready, and PR last it this run

**Comment by GuillaumeGomez** [comment]
\o/

**Pull request merged**
