### PR TITLE
Add all properties

### PR DESCRIPTION
**Pull request by EPashkin**
Result solving of https://github.com/gtk-rs/gir/issues/304

Currently just sample, as all properties added without check for duplicates.

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
This is so awesome! Did you remove the methods that were implemented by hand too? It'd be fun to have the same method implemented in an `*Ext` trait and inside the struct directly. ;)

**Comment by EPashkin** [comment]
Thanks for reminder. I will do after done with duplicate cleanup.

**Comment by EPashkin** [comment]
:tada: First build-able version.

**Comment by GuillaumeGomez** [comment]
🎉

**Comment by EPashkin** [comment]
Almost all properties generated.
As last 15 properties with unsupported types (gdk::RGBA, &[&str], GLib.Variant, pango::AttrList, ..),
so this code will be not changed (may be with exception of removing some properties that already presents in parent).
I still need do parent check, some refactoring in gir, and find & remove manual properties here (it all may take some time).
`gio` also affected by properties generation, I add PR later.

**Comment by EPashkin** [comment]
@GuillaumeGomez, I checked manual parts and don't found any conflicting with properties method.
Also parent properties check shows none conflict, so I removed it from `gir` code.

**Comment by GuillaumeGomez** [comment]
Perfect, thanks a lot! Anything else you want to do on this PR or can I merge it?

**Comment by EPashkin** [comment]
It not ready for merge, as no gir update

**Comment by EPashkin** [comment]
Final version, ready for merge

**Comment by GuillaumeGomez** [comment]
Thanks for your amazing work!

**Pull request merged**
