### PR TITLE
Value get result

### PR DESCRIPTION
**Pull request by fengalin**
See gtk-rs/glib#513 & gtk-rs/gir#825

### CODE REVIEW

**Comment by sdroege** [comment]
:+1:

**Comment by GuillaumeGomez** [comment]
:+1:

**Comment by fengalin** [comment]
Ooops! Forgot the examples. Give me 10mn more please :)

**Comment by sdroege** [comment]
@GuillaumeGomez no need to wait for CI btw. But once this is in the examples PR will be green again finally :)

**Comment by GuillaumeGomez** [comment]
Euuuuh... Still need to confirm for syntax check so I'll wait for failure in any case.

**Comment by fengalin** [comment]
Sorry for the last-minute change...

**Comment by GuillaumeGomez** [comment]
No need to apologize for code improvements.

**Comment by sdroege** [comment]
Need to run `cargo fmt` :)

**Comment by fengalin** [comment]
> Need to run cargo fmt :)

You mean, for the manual implementations?

**Comment by sdroege** [comment]
> You mean, for the manual implementations?

A previous PR was merged without `cargo fmt`, yes.

**Comment by fengalin** [comment]
Shall I had a commit here for that?

**Comment by sdroege** [comment]
Yeah, another commit on top of yours. Then the CI is at least in theory green here :)

**Comment by fengalin** [comment]
I forgot to rebase... That's why it didn't show up before.

**Comment by sdroege** [comment]
Yay, now we can get it in :)

**Comment by fengalin** [comment]
\o/ @GuillaumeGomez let's click!

**Comment by fengalin** [comment]
Note: Appveyor / Windows 32bits keeps on failing on `cargo test` with a rather unexplicit symptom:

```
error: test failed, to rerun pass '--lib'
Command exited with code -1073741511
```

The other platforms (including Appveyor / Windows 64bits) don't show this behaviour. See also: https://github.com/gtk-rs/glib/pull/513#issuecomment-519612520

**Comment by sdroege** [comment]
Known problem, the Windows CI is broken.

**Comment by GuillaumeGomez** [comment]
Thanks!

**Pull request merged**
