### PR TITLE
Update rust version in appveyor script

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
cc @gkoz

### CODE REVIEW

**Comment by EPashkin** [comment]
:+1:

**Comment by gkoz** [comment]
We should start doing it [like this](https://github.com/gtk-rs/gio/blob/master/appveyor.yml#L11-L14) already.

**Comment by GuillaumeGomez** [comment]
Indeed. I update.

**Comment by GuillaumeGomez** [comment]
Done.

**Comment by gkoz** [comment]
Thanks!

**Pull request merged**
