### PR TITLE
Fix boxing in async func

### PR DESCRIPTION
**Pull request by EPashkin**
Part of https://github.com/gtk-rs/gir/issues/807

cc @GuillaumeGomez , @sdroege

### CODE REVIEW

**Comment by EPashkin** [comment]
Seems it depends on https://github.com/gtk-rs/gio/pull/232

**Comment by EPashkin** [comment]
Restarted CI

**Comment by EPashkin** [comment]
Strange error repeated, I don't understand why it was not in gio travis.

Also this code on line 478
```rust
  --> /home/travis/.cargo/git/checkouts/gio-a4b825b310a073b9/1b2740a/src/auto/app_info.rs:863:25

    |

863 |         let uris = uris.map(ToOwned::to_owned);

    |                         ^^^

    |

    = note: the method `map` exists but the following trait bounds were not satisfied:

            `&mut &[&str] : std::iter::Iterator`

            `&mut [&str] : std::iter::Iterator`
```

**Comment by GuillaumeGomez** [comment]
I restarted CIs.

**Comment by EPashkin** [comment]
CI passed

**Comment by GuillaumeGomez** [comment]
👍 

cc @sdroege

**Comment by sdroege** [comment]
:+1: Also as green as it goes, @GuillaumeGomez

**Comment by GuillaumeGomez** [comment]
Thanks @EPashkin !

**Pull request merged**
