### PR TITLE
Fix travis

### PR DESCRIPTION
**Pull request by GuillaumeGomez**

### CODE REVIEW

**Comment by EPashkin** [comment]
Which was error?
With this travis always run examples on gtk master, so don't check changes

**Comment by GuillaumeGomez** [comment]
Yes but otherwise we have this error:

```
error: native library `cairo` is being linked to by more than one package, and can only be linked to by one package
```

For every lib. I still wonder how to overpass. :-/

**Comment by EPashkin** [comment]
You right, cargo don't allow mix crates and `git=` version, I still don't found way to fix it locally
```
error: native library `cairo` is being linked to by more than one package, and can only be linked to by one package

  cairo-sys-rs v0.3.2 (https://github.com/gtk-rs/cairo#37392b30)
  cairo-sys-rs v0.3.2
```

**Comment by EPashkin** [comment]
Seems cargo checks before overriding

**Comment by EPashkin** [comment]
I thought it was regression but seems last nightly works for me too in this case:
```
rustc --version
#rustc 1.15.0-nightly (2217bd771 2016-11-25)
cargo --version
#cargo 0.16.0-nightly (b26d672 2016-11-25)
git clone https://github.com/gtk-rs/gtk.git
cd gtk
mkdir .cargo
echo 'paths = ["."]' > .cargo/config
git clone -q --depth 50 -b pending https://github.com/gtk-rs/examples _examples
cd _examples
cargo build --features
```
Don't understand, why it not work.
Only difference that I doing it manually on windows and travis has `2016-11-24`.

**Comment by EPashkin** [comment]
Checked with archived 2016-11-24 it works too :cry:

**Comment by EPashkin** [comment]
@GuillaumeGomez, can you change file back and run build
https://travis-ci.org/gtk-rs/gtk/jobs/179211820 where cairo error is for crates branch not master.

**Comment by GuillaumeGomez** [comment]
Restarting on master branch.

**Comment by GuillaumeGomez** [comment]
https://travis-ci.org/gtk-rs/gtk/builds/179206097

**Comment by EPashkin** [comment]
Travis says that master working good, so this PR unneeded.

**Comment by GuillaumeGomez** [comment]
Ok!

**Pull request closed without merging**
