### PR TITLE
Change some get_ functions to return non-nullable

### LINKED ISSUE #997: gtk::Entry::get_text should not return an Option
Possible workaround is to call `.get_buffer().get_text()` to get no `Option`.

I think the same applies for

- Label::get_text()
- Label::get_label()

### PR DESCRIPTION
**Pull request by sophie-h**
Closes #997

### CODE REVIEW

**Comment by EPashkin** [comment]
@sophie-h Thanks, 👍 
CI failed on examples that use Option version.

**Comment by sophie-h** [comment]
> CI failed on examples that use Option version.

Should I create a PR for examples too? Unfortunately the pending branch is failing to build for me.

**Comment by GuillaumeGomez** [comment]
The examples pending branch is failing? This is concerning. You're sure you have the last commit?

**Comment by sophie-h** [comment]
I used `build_travis.sh` to build it which probably wasn't the right idea? `cargo build` works. The fixes are in gtk-rs/examples#310.

**Comment by GuillaumeGomez** [comment]
Then I merge here. Thanks!

**Comment by sdroege** [comment]
Thanks!

**Pull request merged**
