### PR TITLE
Remove property `events` getter and setter as we already have normal …

### PR DESCRIPTION
**Pull request by EPashkin**
…variant

Fix https://github.com/gtk-rs/gir/issues/639

cc @GuillaumeGomez, @sdroege

### CODE REVIEW

**Comment by sdroege** [comment]
:+1:

**Comment by GuillaumeGomez** [comment]
Why did it remove two methods? Is it because before it was all automatically generated and now only one is?

**Comment by sdroege** [comment]
The whole point of the commit is to remove these two functions... because we have getters/setters based on functions already, no need to go through the property.

**Comment by GuillaumeGomez** [comment]
Ok. Makes sense. Let's merge it then!

Thanks!

**Pull request merged**
