### PR TITLE
gtk_glue_update

### PR DESCRIPTION
**Pull request by PhnxRbrn**
Addresses #152

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Hi ! Thanks for your PR. It seems fine for me. Do you confirm @gkoz ?

**Comment by gkoz** [comment]
Would it be possible to see appveyor results for this commit?

**Comment by GuillaumeGomez** [comment]
I start it.

**Comment by GuillaumeGomez** [comment]
... Or not. I cannot start a specific build it seems.

@PhnxRbrn: Could you close and reopen this PR in order to restart all checks please?

**Comment by gkoz** [comment]
As I mentioned in the linked issue this PR isn't strictly necessary, so I'd also be fine with just closing it.

**Pull request closed without merging**
