### PR TITLE
Bump versions

### PR DESCRIPTION
**Pull request by gkoz**

### CODE REVIEW

**Comment by EPashkin** [comment]
Don't want before this remove `IsA<Buildable>` constraint in `Builder::get_object` ?

**Comment by EPashkin** [comment]
Or its just forgotten bump after 0.7 publishing?

**Comment by gkoz** [comment]
The goal is to make the version different from crates.io to avoid that kind of confusion, not to follow semver in the master branch (that wouldn't work too well anyway).

**Comment by gkoz** [comment]
The examples build in travis hits the limitation of cargo path overrides but the gtk part seems to build cleanly.

**Comment by EPashkin** [comment]
IMHO no way update gtk system versions without broken builds, so why just not merge all modules and update `examples` last for real check?

**Comment by gkoz** [comment]
I'll take the liberty to merge this because the rest of PRs were approved and keeping this one open will just break someone's build.

**Comment by GuillaumeGomez** [comment]
Absolutely, you did well. Sorry, I didn't see it... :-/

**Pull request merged**
